In [2]:
import numpy as np

In [3]:
#1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива."

kolonki = np.loadtxt('minutes_n_ingredients.csv', max_rows=1, dtype=str, delimiter=',')
dannie = np.loadtxt('minutes_n_ingredients.csv', skiprows=1, dtype=np.int32, delimiter=',')

raw_indices=[0,1,2,3,4]
dannie[raw_indices]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

In [11]:
 #2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого."
column = 1
print(f"Минимальное: {np.min(dannie[:, column])}", f"Максимальное: {np.max(dannie[:, column])}", f'Среднее: {np.mean(dannie[:, column])}', f"Медиана: {np.median(dannie[:, column])}", sep='\n', end='\n\n')
column = 2
print(f"Минимальное: {np.min(dannie[:, column])}", f"Максимальное: {np.max(dannie[:, column])}", f'Среднее: {np.mean(dannie[:, column])}', f"Медиана: {np.median(dannie[:, column])}", sep='\n', end='\n\n')



Минимальное: 0
Максимальное: 2147483647
Среднее: 21601.00169
Медиана: 40.0

Минимальное: 1
Максимальное: 39
Среднее: 9.05528
Медиана: 9.0



In [6]:
 #3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. "
time_out = dannie.copy()
q_3 = np.quantile(time_out[:, 1], q=0.75, axis=0)
time_out[:, 1][time_out[:, 1] > q_3] = q_3

time_out

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]], dtype=int32)

In [8]:
#4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1."
bez_0 = time_out.copy()
good_day = bez_0[:, 1] == 0
nuli = np.count_nonzero(good_day)
bez_0[:, 1][good_day] = 1

nuli
bez_0

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]], dtype=int32)

In [9]:
  #5. Посчитайте, сколько уникальных рецептов находится в датасете."
unique_items = np.unique(bez_0[:, 1:], axis=0).shape[0]
unique_items

1135

In [10]:
#6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?"
len(np.unique(bez_0[:, 2]))

37

In [ ]:
#7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов."
bez_0[bez_0[:, 2] <= 5]

In [12]:
#8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета"
temp = bez_0.copy()
results = (temp[:,2]/temp[:,1])
results
results.max()

24.0

In [13]:
#9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью"
the_best_of_100 = np.argsort(bez_0[:, 1])[:-100:-1]
bez_0[the_best_of_100][:, 2].mean()

9.94949494949495

In [15]:
#10. Выберите случайным образом и выведите информацию о 10 различных рецептах"

dannie[np.random.randint(dannie.shape[0], size=10), :]

array([[ 98800,      6,      4],
       [197496,     22,      6],
       [361848,     50,      6],
       [327564,     10,      6],
       [363413,    365,      5],
       [ 82264,      8,      6],
       [474496,     60,     14],
       [149377,     75,     16],
       [179809,     35,     12],
       [452950,     20,      8]], dtype=int32)

In [16]:
 #11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего."
not_bad_percent = bez_0[the_best_of_100][:, 2].mean()
good_day = dannie[:, 2] < not_bad_percent
print(len(dannie[good_day])/len(dannie) * 100)

58.802


In [17]:
 #12. Назовем \"простым\" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае."

added_column = dannie.copy()
good_day = (dannie[:, 1] <= 20) & (dannie[:, 2] <= 5)
column = good_day.astype(int)
added_column = np.column_stack([added_column, column])
print(added_column)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


In [19]:
 #13. Выведите процент \"простых\" рецептов в датасете"

good_day = added_column[:, 3] == 1
temp = added_column[:, 3][good_day]
len(temp)/len(added_column) * 100

9.552

In [20]:

    #14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива."

short_arr = dannie[dannie[:,1] < 10]
good_day = (dannie[:,1] >= 10) & (dannie[:,1] < 20)
standard_arr = dannie[good_day]
long_arr = dannie[20 <= dannie[:,1]]

crop_value = np.min([short_arr.shape[0], standard_arr.shape[0], long_arr.shape[0]])

result_arr = np.array([short_arr[:crop_value], standard_arr[:crop_value], long_arr[:crop_value]])
result_arr

array([[[ 67660,      5,      6],
        [366174,      7,      9],
        [204134,      5,      3],
        ...,
        [420725,      5,      3],
        [  4747,      0,      9],
        [370915,      5,      4]],

       [[ 94746,     10,      6],
        [ 33941,     18,      9],
        [446597,     15,      5],
        ...,
        [  9831,     15,      7],
        [335859,     12,     14],
        [256812,     10,      3]],

       [[127244,     60,     16],
        [ 23891,     25,      7],
        [157911,     60,     14],
        ...,
        [168901,     25,      7],
        [392339,     35,     13],
        [206732,     45,     10]]], dtype=int32)